name: Deploy to EC2

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Create the app directory if it doesn't exist
          mkdir -p /home/ubuntu/app

          # Navigate to the directory where your Dockerfile will be used
          cd /home/ubuntu/app

          # Clone the latest version of your repository in the app directory
          git clone https://github.com/vinod-kumar-dev/ReactApp .

          # Build the Docker image using the Dockerfile from the repository
          docker build -t your-image-name:latest .

          # Optionally, remove old containers or images
          docker container prune -f
          docker image prune -f

          # Run the Docker container
          docker run -d --name react-app-first -p 80:80 your-image-name:latest
        EOF
